# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Buen estado'), (2, 'Mal estado'), (3, 'Muy mal estado')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('fecha_nac', models.DateField(verbose_name='fecha de nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_10', models.CharField(max_length=13)),
                ('n_paginas', models.PositiveIntegerField(max_length=8)),
                ('idioma', models.CharField(max_length=20)),
                ('cantidad', models.PositiveIntegerField(max_length=8)),
                ('anno', models.DateField(verbose_name='fecha de publicacion')),
                ('tapa', models.SmallIntegerField(choices=[(1, 'Tapa blanda'), (2, 'Tapa dura')], max_length=1)),
                ('encuadernado', models.SmallIntegerField(choices=[(1, 'Encuadernado rustico'), (2, 'Encuadernado encartonado'), (3, 'Encuadernado carton\xe9'), (4, 'Encuadernado de tapa suelta')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('edicion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Libreros.Edicion')),
            ],
        ),
        migrations.CreateModel(
            name='Librero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('subtitulo', models.CharField(max_length=40)),
                ('resenna', models.TextField(max_length=600)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Libreros.Autor')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Libreros.Coleccion')),
                ('generos', models.ManyToManyField(to='Gestion_Libreros.Genero')),
                ('librero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Libreros.Librero')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Libreros.Editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='tags',
            field=models.ManyToManyField(to='Gestion_Libreros.Tag'),
        ),
        migrations.AddField(
            model_name='edicion',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Libreros.Libro'),
        ),
        migrations.AddField(
            model_name='edicion',
            name='sello',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Libreros.Sello'),
        ),
        migrations.AddField(
            model_name='autor',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Libreros.Pais'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='edicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Libreros.Edicion'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='librero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Libreros.Librero'),
        ),
    ]
