# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Libreros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='estado',
            field=models.SmallIntegerField(choices=[(1, 'Buen estado'), (2, 'Mal estado'), (3, 'Muy mal estado')]),
        ),
        migrations.AlterField(
            model_name='edicion',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='edicion',
            name='encuadernado',
            field=models.SmallIntegerField(choices=[(1, 'Encuadernado rustico'), (2, 'Encuadernado encartonado'), (3, 'Encuadernado carton\xe9'), (4, 'Encuadernado de tapa suelta')]),
        ),
        migrations.AlterField(
            model_name='edicion',
            name='n_paginas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='edicion',
            name='tapa',
            field=models.SmallIntegerField(choices=[(1, 'Tapa blanda'), (2, 'Tapa dura')]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='subtitulo',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
